# Generated by Django 5.2.11 on 2026-03-04 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_contactmessage_alter_experience_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True, help_text='Extended About Me paragraph shown in the About section.'),
        ),
    ]
