# Generated by Django 5.2.11 on 2026-03-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_profile_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill_type',
            field=models.CharField(choices=[('Technical', 'Technical'), ('Security', 'Security'), ('Soft', 'Soft')], default='Technical', max_length=20),
        ),
    ]
