# Generated by Django 5.2.11 on 2026-03-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_skill_skill_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='work_mode',
            field=models.CharField(blank=True, choices=[('On-site', 'On-site'), ('Remote', 'Remote'), ('Hybrid', 'Hybrid')], max_length=20),
        ),
    ]
