# Generated by Django 5.2.11 on 2026-03-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_alter_project_options_alter_skill_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(25, 'Beginner'), (50, 'Intermediate'), (75, 'Advanced'), (100, 'Expert')], default=75),
        ),
    ]
